# Generated by Django 5.1.4 on 2025-01-09 07:06

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reason',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
